name: zkEngine CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt --check
        run: cargo fmt -- --check

      - name: Run cargo clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings
